### PR TITLE
fpm ini control

### PR DESCRIPTION
**Pull request by ynuyasha**
### Description

Add configuration of fpm php.ini with template piloted by default['php']['fpm_ini_control']

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by ynuyasha** [comment]
someone can help me and tell me what i do to pass checks?

**Comment by Xorima** [comment]
Hi @ynuyasha 

I will try to get a look at this, sorry for the failures, could you add a changelog entry though please under `## unreleased`

@damacus what do you think of merging this in anyway?

**Comment by damacus** [comment]
Hi @ynuyasha 
sorry about this, the CircleCI config looks like it's either broken of having some trouble with this PR. I'll look into it and rebase your PR. 

Thanks,
Dan

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ynuyasha** [comment]
anyone can resume this pull and help me?

**Comment by Xorima** [comment]
if you run a `cookstyle -a` it should work mate, just make sure you have the latest chef-workstation

**Comment by damacus** [comment]
I'm going to merge this one in and get the linting sorted out in another PR shortly

**Pull request merged**
