### PR TITLE
Include extension priority on the specified format to the extension file

### LINKED ISSUE #293: Priority of extensions ignored
## :ghost: Brief Description

The priority of extensions is entered as a parameter but not rendered on the template

## :pancakes: Cookbook version

7.1.0

## :woman_cook:  Chef-Infra Version

16.1.16

## :tophat: Platform details

Ubuntu 20.04

## Steps To Reproduce

Pass a priority to the resource php_pear:

```
php_pear 'raphf' do
  action :install
  version '2.0.1'
  channel 'pecl.php.net'
  priority '99'
end
```

Verify that the extension file created does NOT contain the given priority.

## :police_car: Expected behavior

A line with the priority (on this specific format) in the extension file created

`; priority=99`

### PR DESCRIPTION
**Pull request by mdiniz**
Signed-off-by: Marcelo Diniz <marudiniz@gmail.com>

# Description

Include extension priority on the specified format to the extension file

## Issues Resolved

#293 

## Check List

- [X] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Xorima** [comment]
Hey @mdiniz 

Thanks for this, would it be possible to include tests for this change as well?

Once we get the changelog entry I can get this merged and shipped

**Comment by Xorima** [comment]
Failing tests are not to do with this change, tests for this change are in and passing.

Thank you very much @mdiniz

**Comment by Xorima** [comment]
Released as 7.2.0

**Pull request merged**
